# Clear Temp Locations
#{
<#
.SYNOPSIS
    Removes the contents of common temp file locations used by Exclaimer
.USAGE
    Use in a scheduled task to regularly remove the temp files generated by Exclaimer 
    that may not have been cleared
.NOTES
    Email: support@exclaimer.com
    Date: 28th December 2017
.REQUIREMENTS
    None
.VERSION
    1.0 - deleted all .tmp files in the common temp file locations
    2.0 - Updated to only delete temp files in the tmp****.tmp format and to remove these files from each users profile
#>
$wintemp = "$env:WINDIR\Temp"
$nettemp = "$env:WINDIR\serviceprofiles\NetworkService\appdata\local\temp"
$AllUserTemp = "$env:SystemDrive\users\*\appdata\local\Temp"
$othertemp = "C:\temp"
 
Remove-Item $wintemp\tmp****.tmp -Recurse -Force
Remove-Item $nettemp\tmp****.tmp -Recurse -Force
Get-ChildItem $AllUserTemp'\tmp****.tmp' -Recurse | Remove-Item -Force -EA SilentlyContinue
$exists = Test-Path -Path $othertemp
 
If ($exists -eq "True") {
  Remove-Item $othertemp\tmp****.tmp -Recurse -Force
  }